model:
  id: "my-model"

build_info:
  python_version: "3.12"
  image: "lmsysorg/sglang:v0.5.8.post1"

compute:
  instance: g5.xlarge

checkpoints:
  repo_id: google/gemma-3-1b-it
  type: huggingface
  when: runtime
